const works = [
  {
    id: 1,
    title: "Google Clone",
    category: "frontend",
    tech: ["HTML", "CSS"],
    img: "google_clone.webp",
    link: "https://pritishraj04.github.io/google-clone/",
    desc: "Frontend project Google Clone made using plain HTML & CSS. This project focuses on creating reponsive mobile first development techniques.",
  },
  {
    id: 2,
    title: "Laundry App",
    category: "fullstack",
    tech: ["Sveltekit", "CSS", "Supabase"],
    img: "lgini.webp",
    link: "https://mystifying-goodall-ca2cf8.netlify.app/",
    desc: "Full Stack project Laundry App made using Sveltekit, CSS as frontend & supabase as backend. This project focuses on quick login/register system integration. This project also features odering and account system. DISCLAIMER: Supabase servises might get paused due to it's reserving resources policy for community users. Please feel free to contact me if the login/register system is not working for you.",
  },
  {
    id: 3,
    title: "Sveltekit Menu",
    category: "frontend",
    tech: ["Sveltekit", "CSS"],
    img: "svelte_menu.webp",
    link: "https://dreamy-pare-0a653b.netlify.app/menu",
    desc: "Frontend project Sveltkit Menu made using Sveltekit, CSS. This project focuses on creating reponsive mobile first development techniques. This project also features glassmorphism styled reactive bill calculator. Add a product to see the total bill amount.",
  },
  {
    id: 4,
    title: "Frontend Mentor Challenge solution",
    category: "frontend",
    tech: ["HTML", "CSS"],
    img: "frontend_mentor_challenge.webp",
    link: "https://pritishraj04.github.io/frontent-mentor-card-purple/",
    desc: "This frontend project is a solution for the frontendmentor.io stats preview card component challenge made using plain HTML, CSS. This project focuses on reponsive mobile first development techniques.",
  },
  {
    id: 5,
    title: "MERN TODO",
    category: "fullstack",
    tech: ["MongoDB", "ExpressJs", "ReactJs", "NodeJs"],
    img: "mern_todo.webp",
    link: "https://pritishmernapp.herokuapp.com/login",
    desc: "Full Stack project MERN TODO made using MongoDB, ExpressJs, ReactJs & NodeJs. This project made during the learning process of MERN stack app. This app is hosted using HEROKU.",
  },
  {
    id: 6,
    title: "React Menu",
    category: "frontend",
    tech: ["ReactJs", "CSS"],
    img: "react_menu.webp",
    link: "https://pritishraj04.github.io/react-menu/",
    desc: "Frontend project React Menu made using ReactJs, CSS. This project focuses on reponsive web design techniques. This project also features numeric entry based reactive bill calculator. Add a product to see the total bill amount.",
  },
  {
    id: 7,
    title: "Resposnsive homepage",
    category: "frontend",
    tech: ["HTML", "CSS"],
    img: "frontend_homepage.webp",
    link: "https://pritishraj04.github.io/frontent-homepage-responsive/",
    desc: "Frontend project Resposnsive homepage made using plain HTML, CSS. This project focuses on reponsive mobile first development techniques.",
  },
];

export default works;
